# $OpenBSD: Makefile,v 1.0 2016/02/02 21:40:12 humanity Exp $

     SUBDIR =
     SUBDIR += autobook
     SUBDIR += diveintopython
     SUBDIR += diveintopython3
     SUBDIR += docbook-guide
     SUBDIR += grokking-the-gimp
     SUBDIR += mason-book
     SUBDIR += svnbook
     SUBDIR += vol3ol
     SUBDIR += vol6a
     SUBDIR += wndw
     SUBDIR += man-pages-posix
     SUBDIR += tex-by-topic

.include <bsd.port.subdir.mk>