# $OpenBSD: Makefile,v 1.0 2016/02/02 21:40:12 humanity Exp $

     SUBDIR =
     SUBDIR += AcePerl
     SUBDIR += bioperl
     SUBDIR += emboss
     SUBDIR += nutdb
     SUBDIR += p5-Bio-ASN1-EntrezGene
     SUBDIR += py-biopython

.include <bsd.port.subdir.mk>