# $OpenBSD: Makefile,v 1.9 2013/10/11 23:48:46 naddy Exp $

COMMENT=	alternative to the standard perl exporter
CATEGORIES=	devel

DISTNAME=	Exporter-Tidy-0.06
REVISION=	1

# PD
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

.include <bsd.port.mk>
