# $OpenBSD: Makefile,v 1.9 2015/01/21 06:13:47 bentley Exp $

COMMENT=	impromptu dumping of data structures for debugging purposes

MODULES=	cpan
DISTNAME=	BFD-0.31
REVISION=	2
CATEGORIES=	devel
# "You may use this software under the terms of the GNU Pulic License, the
#  Artistic License, the BSD license, the MIT license, etc., etc., etc."
PERMIT_PACKAGE_CDROM=	Yes

CPAN_AUTHOR=	RBS

.include <bsd.port.mk>
