# $OpenBSD: Makefile,v 1.0 2016/02/02 21:40:12 humanity Exp $

     SUBDIR =
     SUBDIR += cconv
     SUBDIR += cless
     SUBDIR += libchewing
     SUBDIR += libtabe
     SUBDIR += py-zhCodecs
     SUBDIR += ttfm

.include <bsd.port.subdir.mk>